apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ossg9s9hi-python 
  janus-idp.io/tekton: ossg9s9hi-python
  backstage.io/kubernetes-id: ossg9s9hi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ossg9s9hi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml